name: Release
# Run workflow on commits to the `main` branch
on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt-hotspot'
          java-version: '21'
          cache: 'maven'
      - name: Release Maven Central
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          server_id: central
          gpg_private_key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          nexus_username: ${{ secrets.OSSRH_USERNAME }}
          nexus_password: ${{ secrets.OSSRH_TOKEN }}
